FROM sickcodes/docker-osx:latest

WORKDIR /app
COPY . .

RUN brew install python3
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt

RUN cd agent && pyinstaller agent_macos.spec 