# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x06mirage\"y\n\nSystemInfo\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12\x0c\n\x04\x61rch\x18\x04 \x01(\t\x12\x0b\n\x03pid\x18\x05 \x01(\t\x12\x0e\n\x06\x64omain\x18\x06 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x07 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0e\x43heckinRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"$\n\x0f\x43heckinResponse\x12\x11\n\thas_tasks\x18\x01 \x01(\x08\"\x1f\n\x0bTaskRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"4\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\t\"+\n\x0cTaskResponse\x12\x1b\n\x05tasks\x18\x01 \x03(\x0b\x32\x0c.mirage.Task\"m\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08\x61gent_id\x18\x05 \x01(\tB\x08\n\x06_error\"2\n\x0eResultResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"c\n\tFileChunk\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\x12\x10\n\x08\x61gent_id\x18\x05 \x01(\t\"0\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb6\x02\n\x0c\x41gentService\x12:\n\x08Register\x12\x12.mirage.SystemInfo\x1a\x18.mirage.RegisterResponse\"\x00\x12<\n\x07\x43heckin\x12\x16.mirage.CheckinRequest\x1a\x17.mirage.CheckinResponse\"\x00\x12\x37\n\x08GetTasks\x12\x13.mirage.TaskRequest\x1a\x14.mirage.TaskResponse\"\x00\x12:\n\nSendResult\x12\x12.mirage.TaskResult\x1a\x16.mirage.ResultResponse\"\x00\x12\x37\n\x08SendFile\x12\x11.mirage.FileChunk\x1a\x14.mirage.FileResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMINFO']._serialized_start=23
  _globals['_SYSTEMINFO']._serialized_end=144
  _globals['_REGISTERRESPONSE']._serialized_start=146
  _globals['_REGISTERRESPONSE']._serialized_end=198
  _globals['_CHECKINREQUEST']._serialized_start=200
  _globals['_CHECKINREQUEST']._serialized_end=234
  _globals['_CHECKINRESPONSE']._serialized_start=236
  _globals['_CHECKINRESPONSE']._serialized_end=272
  _globals['_TASKREQUEST']._serialized_start=274
  _globals['_TASKREQUEST']._serialized_end=305
  _globals['_TASK']._serialized_start=307
  _globals['_TASK']._serialized_end=359
  _globals['_TASKRESPONSE']._serialized_start=361
  _globals['_TASKRESPONSE']._serialized_end=404
  _globals['_TASKRESULT']._serialized_start=406
  _globals['_TASKRESULT']._serialized_end=515
  _globals['_RESULTRESPONSE']._serialized_start=517
  _globals['_RESULTRESPONSE']._serialized_end=567
  _globals['_FILECHUNK']._serialized_start=569
  _globals['_FILECHUNK']._serialized_end=668
  _globals['_FILERESPONSE']._serialized_start=670
  _globals['_FILERESPONSE']._serialized_end=718
  _globals['_AGENTSERVICE']._serialized_start=721
  _globals['_AGENTSERVICE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
